name: Get Job ID
author: Austen Stone
description: Get the Job ID of the current job
branding:
  icon: "plus"
  color: "blue"

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false

runs:
  using: "composite"
  steps:
    - run: echo $(gh run view ${{ github.run_id }} --json jobs | jq -r '.jobs[] | select(.name == "${{ github.job }}") | .databaseId') >> "$GITHUB_OUTPUT"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}