name: Usage
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: job-id
      - run: echo $GITHUB_JOB_ID
        env:
          GITHUB_JOB_ID: ${{ steps.job-id.outputs.job-id }}